### ISSUE TITLE
I have a issues.What should I do?

### ISSUE THREAD

**Issue by anybye** [sbaron/TauLabs#2]
I run "make bl_naze32" on windows with QT5.4.Error message is
 mingw32-make[1]:*** No rule to make target 'bin'. stop.
makefile:878: recipe for target 'bl_naze32_bin' failed.

But "make bl_flyingf3" works well.

I don't know what should I do. Can you help me ?

**Comment by sbaron** [comment]
Hi,

There's no boot loader (bl) for naze32, because the hardware doesn't support it.
You have to build the firmware (fw_naze32) and directly upload it on the board using the "STM Flash Loader" tool.

Regards.
